-- Seed universities in Thailand from Wikipedia
-- Source: https://en.wikipedia.org/wiki/List_of_universities_and_colleges_in_Thailand

INSERT INTO "University" (id, name, code, province, country, "createdAt", "updatedAt")
VALUES
(gen_random_uuid(), 'Asia-Pacific International University', 'AIU', 'Saraburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Assumption University', 'AU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bangkok University', 'BU', 'Pathum Thani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bangkokthonburi University', 'BTU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bansomdejchaopraya Rajabhat University', 'BSRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bunditpatanasilpa Institute', 'BPI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Burapha University', 'BUU', 'Chonburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Buri Ram Rajabhat University', 'BRU', 'Buriram', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chaiyaphum Rajabhat University', 'CPRU', 'Chaiyaphum', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chandrakasem Rajabhat University', 'CRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chaopraya University', 'CPU', 'Nakhon Sawan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Mai Rajabhat University', 'CMRU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Mai University', 'CMU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Rai Rajabhat University', 'CRRU', 'Chiang Rai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chitralada Technology Institute', 'CDTI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Christian University', 'CTU', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulabhorn Graduate Institute', 'CGI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulachomklao Royal Military Academy', 'CRMA', 'Nakhon Nayok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulalongkorn University', 'CU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Civil Aviation Training Center', 'CATC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Command and General staff College', 'CGSC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Dhonburi Rajabhat University', 'DRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Dhurakij Pundit University', 'DPU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'E-sarn University', 'ESU', 'Khon Kaen', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Eastern Asia University', 'EAU', 'Pathumthani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Fatoni University', 'YIU', 'Pattani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'HRH Princess Chulabhorn College of Medical Science', 'PCCMS', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Hatyai University', 'HU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Huachiew Chalermprakiet University', 'HCU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Irrigation College', 'IRID', 'Nonthaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Judge Advocate General School Thailand', 'JAG', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kalasin University', 'KSU', 'Kalasin', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kamphaeng Phet Rajabhat University', 'KPRU', 'Kamphaeng Phet', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kanchanaburi Rajabhat University', 'KRU', 'Kanchanaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kasem Bundit University', 'KBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kasetsart University', 'KU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Khon Kaen University', 'KKU', 'Khon Kaen', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'King Mongkut''s Institute of Technology Ladkrabang', 'KMITL', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'King Mongkut''s University of Technology North Bangkok', 'KMUTNB', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'King Mongkut''s University of Technology Thonburi', 'KMUTT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Krirk University', 'KRIRK', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Lampang Rajabhat University', 'LPRU', 'Lampang', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Loei Rajabhat University', 'LRU', 'Loei', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mae Fah Luang University', 'MFU', 'Chiang Rai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Maejo University', 'MJU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Maha Sarakham Rajabhat University', 'RMU', 'Maha Sarakham', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahachulalongkornrajavidyalaya University', 'MCU', 'Phra nakhon Si Ayutthaya', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahamakut Buddhist University', 'MBU', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahanakorn University of Technology', 'MUT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahasarakham University', 'MSU', 'Maha Sarakham', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahidol University', 'MU', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Merchant Marine Training Center', 'MMTC', 'Samut Prakan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Muban Chom Bung Rajabhat University', 'MCRU', 'Ratchaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Pathom Rajabhat University', 'NPRU', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Phanom University', 'NPU', 'Nakhon Phanom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Ratchasima Rajabhat University', 'NRRU', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Sawan Rajabhat University', 'NSRU', 'Nakhon Sawan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Si Thammarat Rajabhat University', 'NSTRU', 'Nakhon Si Thammarat', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Naresuan University', 'NU', 'Phitsanulok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nation University ( Yonok University )', 'NTU', 'Lampang', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'National Defence College', 'NDC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'National Institute of Development Administration (NIDA)', 'NIDA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Navaminda Kasatriyadhiraj Royal Thai Air Force Academy', 'RTAFA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Navamindradhiraj University', 'NMU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Bangkok University', 'NBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Chiang Mai University', 'NCU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Eastern University', 'NEU', 'Khon Kaen', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pathumthani University', 'PTU', 'Pathum Thani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pathumwan Institute of Technology', 'PTWIT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Payap University', 'PYU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phetchabun Rajabhat University', 'PCRU', 'Phetchabun', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phetchaburi Rajabhat University', 'PBRU', 'Phetchaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phramongkutklao College of Medicine', 'PCM', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phranakhon Rajabhat University', 'PNRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phranakhon Si Ayutthaya Rajabhat University', 'ARU', 'Phra Nakhon Si Ayutthaya', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phuket Rajabhat University', 'PKRU', 'Phuket', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pibulsongkram Rajabhat University', 'PSRU', 'Phitsanulok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Police Nursing College', 'PNC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Praboromarajchanok Institute', 'PI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Prince of Songkla University', 'PSU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Princess Galyani Vadhana Institute of Music', 'PGVIM', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Princess of Naradhiwas University', 'PNU', 'Narathiwat', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Isan', 'RMUTI', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Krungthep', 'RMUTK', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Lanna', 'RMUTL', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Phra Nakhon', 'RMUTP', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Rattanakosin', 'RMUTR', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Srivijaya', 'RMUTSV', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Suvarnabhumi', 'RMUTSB', 'Phra Nakhon Si Ayutthaya', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Tawan-ok', 'RMUTTO', 'Chonburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Thanyaburi', 'RMUTT', 'Pathum Thani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajanagarindra Rajabhat University', 'RRU', 'Chachoengsao', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rambhai Barni Rajabhat University', 'RBRU', 'Chantaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ramkhamhaeng University', 'RU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rangsit University', 'RSU', 'Pathumthani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ratchathani University', 'RTU', 'Ubon Ratchathani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rattana Bundit University', 'RBAC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Roi Et Rajabhat University', 'RERU', 'Roi Et', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Police Cadet Academy', 'RPCA', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Air Force Nursing College', 'RTAFNC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Navy Academy', 'RTNA', 'Samut Prakan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Navy College of Nursing', 'RTNCN', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Saint John''s University', 'SJU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sakon Nakhon Rajabhat University', 'SNRU', 'Sakon Nakhon', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Shinawatra University', 'SIU', 'Pathumthani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Siam University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Silpakorn University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sisaket Rajabhat University', 'SSKRU', 'Sisaket', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Songkhla Rajabhat University', 'SKRU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'South-East Asia University', 'SAU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Srinakharinwirot University', 'SWU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sripatum University', 'SPU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Srisavarindhira Thai Red Cross Institute of Nursing', 'STIN', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Stamford International University', 'STIU', 'Phetchaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suan Dusit University', 'SDU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suan Sunandha Rajabhat University', 'SSRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sukhothai Thammathirat Open University', 'STOU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suranaree University of Technology', 'SUT', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suratthani Rajabhat University', 'SRU', 'Surat Thani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Surin Rajabhat University', 'SRRU', 'Surin', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thailand National Sports University', 'TNSU', 'Chonburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thaksin University', 'TSU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thammasat University', 'TU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'The Eastern University of Management and Technology', 'UMT', 'Ubon Ratchathani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'The Far Eastern University', 'FEU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'The University of Central Thailand', 'TUCT', 'Nakhon Sawan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thepsatri Rajabhat University', 'TRU', 'Lopburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thonburi University', 'ThonburiU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ubon Ratchathani Rajabhat University', 'UBRU', 'Ubon Ratchathani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ubon Ratchathani University', 'UBU', 'Ubon Ratchathani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Udon Thani Rajabhat University', 'UDRU', 'Udon Thani', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'University of Phayao', 'UP', 'Phayao', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'University of the Thai Chamber of Commerce', 'UTCC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Uttaradit Rajabhat University', 'URU', 'Uttaradit', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Valaya Alongkorn Rajabhat University', 'VRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Vongchavalitkul University', 'VU', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Walailak University', 'WU', 'Nakhon Si Thammarat', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Webster University Thailand', 'WUTC', 'Phetchaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Western University', 'WTU', 'Kanchanaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Yala Rajabhat University', 'YRU', 'Yala', 'Thailand', NOW(), NOW())
(gen_random_uuid(), 'Chulabhorn Royal Academy', 'CRA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Institute of Community Colleges', 'ICCS', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bangkok Suvarnabhumi University', 'BSU', 'Samut Prakan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Dusit Thani College', 'DTC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'International Buddhist College', 'IBC', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kantana Institute', 'KI', 'Nakhon Pathom', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Panyapiwat Institute of Management', 'PIM', 'Nonthaburi', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thai-Nichi Institute of Technology', 'TNI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'St Theresa International College', 'STIC', 'Nakhon Nayok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Southeast Bangkok College', 'SBC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suvarnabhumi Institute of Technology', 'SIT', 'Samut Prakan', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Vidyasirimedhi Institute of Science and Technology', 'VISTEC', 'Rayong', 'Thailand', NOW(), NOW())
ON CONFLICT (name) DO NOTHING;
