-- Seed Thai Provinces from geography.json
-- Run this SQL script to populate the Province table
-- Generated from geography.json

INSERT INTO "Province" ("id", "name", "thname", "code", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Bangkok', 'กรุงเทพมหานคร', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Samut Prakan', 'สมุทรปราการ', '11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nonthaburi', 'นนทบุรี', '12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Pathum Thani', 'ปทุมธานี', '13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phra Nakhon Si Ayutthaya', 'พระนครศรีอยุธยา', '14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Ang Thong', 'อ่างทอง', '15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Loburi', 'ลพบุรี', '16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sing Buri', 'สิงห์บุรี', '17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chai Nat', 'ชัยนาท', '18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Saraburi', 'สระบุรี', '19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chon Buri', 'ชลบุรี', '20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Rayong', 'ระยอง', '21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chanthaburi', 'จันทบุรี', '22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Trat', 'ตราด', '23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chachoengsao', 'ฉะเชิงเทรา', '24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Prachin Buri', 'ปราจีนบุรี', '25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Nayok', 'นครนายก', '26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sa Kaeo', 'สระแก้ว', '27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Ratchasima', 'นครราชสีมา', '30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Buri Ram', 'บุรีรัมย์', '31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Surin', 'สุรินทร์', '32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Si Sa Ket', 'ศรีสะเกษ', '33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Ubon Ratchathani', 'อุบลราชธานี', '34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Yasothon', 'ยโสธร', '35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chaiyaphum', 'ชัยภูมิ', '36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Amnat Charoen', 'อำนาจเจริญ', '37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bueng Kan', 'บึงกาฬ', '38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nong Bua Lam Phu', 'หนองบัวลำภู', '39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Khon Kaen', 'ขอนแก่น', '40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Udon Thani', 'อุดรธานี', '41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Loei', 'เลย', '42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nong Khai', 'หนองคาย', '43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Maha Sarakham', 'มหาสารคาม', '44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Roi Et', 'ร้อยเอ็ด', '45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kalasin', 'กาฬสินธุ์', '46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sakon Nakhon', 'สกลนคร', '47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Phanom', 'นครพนม', '48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Mukdahan', 'มุกดาหาร', '49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chiang Mai', 'เชียงใหม่', '50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Lamphun', 'ลำพูน', '51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Lampang', 'ลำปาง', '52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Uttaradit', 'อุตรดิตถ์', '53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phrae', 'แพร่', '54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nan', 'น่าน', '55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phayao', 'พะเยา', '56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chiang Rai', 'เชียงราย', '57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Mae Hong Son', 'แม่ฮ่องสอน', '58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Sawan', 'นครสวรรค์', '60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Uthai Thani', 'อุทัยธานี', '61', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kamphaeng Phet', 'กำแพงเพชร', '62', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Tak', 'ตาก', '63', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Sukhothai', 'สุโขทัย', '64', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phitsanulok', 'พิษณุโลก', '65', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phichit', 'พิจิตร', '66', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phetchabun', 'เพชรบูรณ์', '67', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Ratchaburi', 'ราชบุรี', '70', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kanchanaburi', 'กาญจนบุรี', '71', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Suphan Buri', 'สุพรรณบุรี', '72', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Pathom', 'นครปฐม', '73', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Samut Sakhon', 'สมุทรสาคร', '74', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Samut Songkhram', 'สมุทรสงคราม', '75', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phetchaburi', 'เพชรบุรี', '76', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Prachuap Khiri Khan', 'ประจวบคีรีขันธ์', '77', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Nakhon Si Thammarat', 'นครศรีธรรมราช', '80', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Krabi', 'กระบี่', '81', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phangnga', 'พังงา', '82', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phuket', 'ภูเก็ต', '83', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Surat Thani', 'สุราษฎร์ธานี', '84', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Ranong', 'ระนอง', '85', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Chumphon', 'ชุมพร', '86', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Songkhla', 'สงขลา', '90', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Satun', 'สตูล', '91', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Trang', 'ตรัง', '92', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Phatthalung', 'พัทลุง', '93', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Pattani', 'ปัตตานี', '94', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Yala', 'ยะลา', '95', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Narathiwat', 'นราธิวาส', '96', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") 
DO UPDATE SET 
  "thname" = EXCLUDED."thname",
  "code" = EXCLUDED."code",
  "updatedAt" = CURRENT_TIMESTAMP;
