-- Generated University Seeds
INSERT INTO "University" ("id", "name", "code", "province", "country", "createdAt", "updatedAt")
VALUES
(gen_random_uuid(), 'Asia-Pacific International University', 'AIU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Assumption University', 'AU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bangkok University', 'BU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bangkokthonburi University', 'BU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bansomdejchaopraya Rajabhat University', 'BRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Bunditpatanasilpa Institute', 'BI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Burapha University', 'BU', 'Chon Buri', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Buri Ram Rajabhat University', 'BRRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chaiyaphum Rajabhat University', 'CRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chandrakasem Rajabhat University', 'CRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chaopraya University', 'CU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Mai Rajabhat University', 'CMRU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Mai University', 'CMU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chiang Rai Rajabhat University', 'CRRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chitralada Technology Institute', 'CTI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Christian University', 'CU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulabhorn Graduate Institute', 'CGI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulachomklao Royal Military Academy', 'CRMA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulalongkorn University', 'CU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Civil Aviation Training Center', 'CATC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Command and General staff College', 'CAGSC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Dhonburi Rajabhat University', 'DRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Dhurakij Pundit University', 'DPU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'E-sarn University', 'EU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Eastern Asia University', 'EAU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Fatoni University', 'FU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'HRH Princess Chulabhorn College of Medical Science', 'HPCCOMS', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Hatyai University', 'HU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Huachiew Chalermprakiet University', 'HCU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Irrigation College', 'IC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Judge Advocate General School Thailand', 'JAGST', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kalasin University', 'KU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kamphaeng Phet Rajabhat University', 'KPRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kanchanaburi Rajabhat University', 'KRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kasem Bundit University', 'KBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Kasetsart University', 'KU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Khon Kaen University', 'KKU', 'Khon Kaen', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahidol University', 'MU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mae Fah Luang University', 'MFLU', 'Chiang Rai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Maejo University', 'MU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahasarakham University', 'MU', 'Maha Sarakham', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Prince of Songkla University', 'POSU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ramkhamhaeng University', 'RU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rangsit University', 'RU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Siam University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Silpakorn University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Srinakharinwirot University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thammasat University', 'TU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Walailak University', 'WU', 'Nakhon Si Thammarat', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Yala Rajabhat University', 'YRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Chulabhorn Royal Academy', 'CRA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Institute of Community Colleges', 'IOCC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Vidyasirimedhi Institute of Science and Technology', 'VIOSAT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Navamindradhiraj University', 'NU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Navaminda Kasatriyadhiraj Royal Thai Air Force Academy', 'NKRTAFA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'University of the Thai Chamber of Commerce', 'UOTTCOC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Naresuan University', 'NU', 'Phitsanulok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pibulsongkram Rajabhat University', 'PRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Krirk University', 'KU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Lampang Rajabhat University', 'LRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Loei Rajabhat University', 'LRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Maha Sarakham Rajabhat University', 'MSRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahachulalongkornrajavidyalaya University', 'MU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahamakut Buddhist University', 'MBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Mahanakorn University of Technology', 'MUOT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Merchant Marine Training Center', 'MMTC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Muban Chom Bung Rajabhat University', 'MCBRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Pathom Rajabhat University', 'NPRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Phanom University', 'NPU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Ratchasima Rajabhat University', 'NRRU', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Sawan Rajabhat University', 'NSRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Nakhon Si Thammarat Rajabhat University', 'NSTRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Bangkok University', 'NBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Chiang Mai University', 'NCMU', 'Chiang Mai', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'North Eastern University', 'NEU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pathumthani University', 'PU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pathumwan Institute of Technology', 'PIOT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Payap University', 'PU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phetchabun Rajabhat University', 'PRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phetchaburi Rajabhat University', 'PRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phramongkutklao College of Medicine', 'PCOM', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phranakhon Rajabhat University', 'PRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phranakhon Si Ayutthaya Rajabhat University', 'PSARU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Phuket Rajabhat University', 'PRU', 'Phuket', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Pibulsongkram Rajabhat University', 'PRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Police Nursing College', 'PNC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Praboromarajchanok Institute', 'PI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Princess Galyani Vadhana Institute of Music', 'PGVIOM', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Princess of Naradhiwas University', 'PONU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Isan', 'RUOTI', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Krungthep', 'RUOTK', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Lanna', 'RUOTL', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Phra Nakhon', 'RUOTPN', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Rattanakosin', 'RUOTR', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Srivijaya', 'RUOTS', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Suvarnabhumi', 'RUOTS', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Tawan-ok', 'RUOTT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajamangala University of Technology Thanyaburi', 'RUOTT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rajanagarindra Rajabhat University', 'RRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rambhai Barni Rajabhat University', 'RBRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Ratchathani University', 'RU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Rattana Bundit University', 'RBU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Roi Et Rajabhat University', 'RERU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Police Cadet Academy', 'RPCA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Air Force Nursing College', 'RTAFNC', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Navy Academy', 'RTNA', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Royal Thai Navy College of Nursing', 'RTNCON', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sakon Nakhon Rajabhat University', 'SNRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Shinawatra University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sisaket Rajabhat University', 'SRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Songkhla Rajabhat University', 'SRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'South-East Asia University', 'SAU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sripatum University', 'SU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Srisavarindhira Thai Red Cross Institute of Nursing', 'STRCION', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Stamford International University', 'SIU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suan Dusit University', 'SDU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suan Sunandha Rajabhat University', 'SSRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Sukhothai Thammathirat Open University', 'STOU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suranaree University of Technology', 'SUOT', 'Nakhon Ratchasima', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Suratthani Rajabhat University', 'SRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Surin Rajabhat University', 'SRU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thailand National Sports University', 'TNSU', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'Thaksin University', 'TU', 'Songkhla', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'The Eastern University of Management and Technology', 'TEUOMAT', 'Bangkok', 'Thailand', NOW(), NOW()),
(gen_random_uuid(), 'The Far Eastern University', 'TFEU', 'Bangkok', 'Thailand', NOW(), NOW())
ON CONFLICT ("name") DO NOTHING;
