UPDATE "University"
SET thname = CASE name
 WHEN 'Asia-Pacific International University' THEN 'มหาวิทยาลัยนานาชาติเอเชียแปซิฟิก'
  WHEN 'Assumption University' THEN 'มหาวิทยาลัยอัสสัมชัญ'
  WHEN 'Bangkok University' THEN 'มหาวิทยาลัยกรุงเทพ'
  WHEN 'Bangkokthonburi University' THEN 'มหาวิทยาลัยกรุงเทพธนบุรี'
  WHEN 'Bansomdejchaopraya Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา'
  WHEN 'Bunditpatanasilpa Institute' THEN 'สถาบันบัณฑิตพัฒนศิลป์'
  WHEN 'Burapha University' THEN 'มหาวิทยาลัยบูรพา'
  WHEN 'Buri Ram Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏบุรีรัมย์'
  WHEN 'Chaiyaphum Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏชัยภูมิ'
  WHEN 'Chandrakasem Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏจันทรเกษม'
  WHEN 'Chaopraya University' THEN 'มหาวิทยาลัยเจ้าพระยา'
  WHEN 'Chiang Mai Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเชียงใหม่'
  WHEN 'Chiang Mai University' THEN 'มหาวิทยาลัยเชียงใหม่'
  WHEN 'Chiang Rai Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเชียงราย'
  WHEN 'Chitralada Technology Institute' THEN 'สถาบันเทคโนโลยีจิตรลดา'
  WHEN 'Christian University' THEN 'มหาวิทยาลัยคริสเตียน'
  WHEN 'Chulabhorn Graduate Institute' THEN 'สถาบันบัณฑิตศึกษาจุฬาภรณ์'
  WHEN 'Chulachomklao Royal Military Academy' THEN 'โรงเรียนนายร้อยพระจุลจอมเกล้า'
  WHEN 'Chulalongkorn University' THEN 'จุฬาลงกรณ์มหาวิทยาลัย'
  WHEN 'Civil Aviation Training Center' THEN 'ศูนย์ฝึกการบินพลเรือน'
  WHEN 'Command and General staff College' THEN 'วิทยาลัยเสนาธิการทหาร'
  WHEN 'Dhonburi Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏธนบุรี'
  WHEN 'Dhurakij Pundit University' THEN 'มหาวิทยาลัยธุรกิจบัณฑิตย์'
  WHEN 'E-sarn University' THEN 'มหาวิทยาลัยอีสาน'
  WHEN 'Eastern Asia University' THEN 'มหาวิทยาลัยอีสเทิร์นเอเชีย'
  WHEN 'Fatoni University' THEN 'มหาวิทยาลัยฟาฏอนี'
  WHEN 'HRH Princess Chulabhorn College of Medical Science' THEN 'วิทยาลัยแพทยศาสตร์ศรีสวางควัฒน'
  WHEN 'Hatyai University' THEN 'มหาวิทยาลัยหาดใหญ่'
  WHEN 'Huachiew Chalermprakiet University' THEN 'มหาวิทยาลัยหัวเฉียวเฉลิมพระเกียรติ'
  WHEN 'Irrigation College' THEN 'วิทยาลัยการชลประทาน'
  WHEN 'Judge Advocate General School Thailand' THEN 'โรงเรียนพระธรรมนูญทหาร'
  WHEN 'Kalasin University' THEN 'มหาวิทยาลัยกาฬสินธุ์'
  WHEN 'Kamphaeng Phet Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏกำแพงเพชร'
  WHEN 'Kanchanaburi Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏกาญจนบุรี'
  WHEN 'Kasem Bundit University' THEN 'มหาวิทยาลัยเกษมบัณฑิต'
  WHEN 'Kasetsart University' THEN 'มหาวิทยาลัยเกษตรศาสตร์'
  WHEN 'Khon Kaen University' THEN 'มหาวิทยาลัยขอนแก่น'
  WHEN 'King Mongkut''s Institute of Technology Ladkrabang' THEN 'สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง'
  WHEN 'King Mongkut''s University of Technology North Bangkok' THEN 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ'
  WHEN 'King Mongkut''s University of Technology Thonburi' THEN 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี'
  WHEN 'Mahidol University' THEN 'มหาวิทยาลัยมหิดล'
  WHEN 'Mae Fah Luang University' THEN 'มหาวิทยาลัยแม่ฟ้าหลวง'
  WHEN 'Maejo University' THEN 'มหาวิทยาลัยแม่โจ้'
  WHEN 'Mahasarakham University' THEN 'มหาวิทยาลัยมหาสารคาม'
  WHEN 'Prince of Songkla University' THEN 'มหาวิทยาลัยสงขลานครินทร์'
  WHEN 'Ramkhamhaeng University' THEN 'มหาวิทยาลัยรามคำแหง'
  WHEN 'Rangsit University' THEN 'มหาวิทยาลัยรังสิต'
  WHEN 'Siam University' THEN 'มหาวิทยาลัยสยาม'
  WHEN 'Silpakorn University' THEN 'มหาวิทยาลัยศิลปากร'
  WHEN 'Srinakharinwirot University' THEN 'มหาวิทยาลัยศรีนครินทรวิโรฒ'
  WHEN 'Thammasat University' THEN 'มหาวิทยาลัยธรรมศาสตร์'
  WHEN 'Walailak University' THEN 'มหาวิทยาลัยวลัยลักษณ์'
  WHEN 'Yala Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏยะลา'
  WHEN 'Chulabhorn Royal Academy' THEN 'ราชวิทยาลัยจุฬาภรณ์'
  WHEN 'Institute of Community Colleges' THEN 'สถาบันวิทยาลัยชุมชน'
  WHEN 'Vidyasirimedhi Institute of Science and Technology' THEN 'สถาบันวิทยสิริเมธี'
  WHEN 'Navamindradhiraj University' THEN 'มหาวิทยาลัยนวมินทราธิราช'
  WHEN 'Navaminda Kasatriyadhiraj Royal Thai Air Force Academy' THEN 'โรงเรียนนายเรืออากาศนวมินทกษัตริยาธิราช'
  WHEN 'University of the Thai Chamber of Commerce' THEN 'มหาวิทยาลัยหอการค้าไทย'
  WHEN 'Naresuan University' THEN 'มหาวิทยาลัยนเรศวร'
  WHEN 'Pibulsongkram Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏพิบูลสงคราม'
  WHEN 'Krirk University' THEN 'มหาวิทยาลัยเกริก'
  WHEN 'Lampang Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏลำปาง'
  WHEN 'Loei Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเลย'
  WHEN 'Maha Sarakham Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏมหาสารคาม'
  WHEN 'Mahachulalongkornrajavidyalaya University' THEN 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย'
  WHEN 'Mahamakut Buddhist University' THEN 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย'
  WHEN 'Mahanakorn University of Technology' THEN 'มหาวิทยาลัยเทคโนโลยีมหานคร'
  WHEN 'Merchant Marine Training Center' THEN 'ศูนย์ฝึกเดินเรือพาณิชย์'
  WHEN 'Muban Chom Bung Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏบ้านจอมบึง'
  WHEN 'Nakhon Pathom Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏนครปฐม'
  WHEN 'Nakhon Phanom University' THEN 'มหาวิทยาลัยนครพนม'
  WHEN 'Nakhon Ratchasima Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏนครราชสีมา'
  WHEN 'Nakhon Sawan Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏนครสวรรค์'
  WHEN 'Nakhon Si Thammarat Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏนครศรีธรรมราช'
  WHEN 'North Bangkok University' THEN 'มหาวิทยาลัยนอร์ทกรุงเทพ'
  WHEN 'North Chiang Mai University' THEN 'มหาวิทยาลัยนอร์ทเชียงใหม่'
  WHEN 'North Eastern University' THEN 'มหาวิทยาลัยภาคตะวันออกเฉียงเหนือ'
  WHEN 'Pathumthani University' THEN 'มหาวิทยาลัยปทุมธานี'
  WHEN 'Pathumwan Institute of Technology' THEN 'สถาบันเทคโนโลยีปทุมวัน'
  WHEN 'Payap University' THEN 'มหาวิทยาลัยพายัพ'
  WHEN 'Phetchabun Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเพชรบูรณ์'
  WHEN 'Phetchaburi Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเพชรบุรี'
  WHEN 'Phramongkutklao College of Medicine' THEN 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า'
  WHEN 'Phranakhon Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏพระนคร'
  WHEN 'Phranakhon Si Ayutthaya Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏพระนครศรีอยุธยา'
  WHEN 'Phuket Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏภูเก็ต'
  WHEN 'Pibulsongkram Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏพิบูลสงคราม'
  WHEN 'Police Nursing College' THEN 'วิทยาลัยพยาบาลตำรวจ'
  WHEN 'Praboromarajchanok Institute' THEN 'สถาบันพระบรมราชชนก'
  WHEN 'Princess Galyani Vadhana Institute of Music' THEN 'สถาบันดนตรีกัลยาณิวัฒนา'
  WHEN 'Princess of Naradhiwas University' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออกเฉียงใต้'
  WHEN 'Rajamangala University of Technology Isan' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน'
  WHEN 'Rajamangala University of Technology Krungthep' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ'
  WHEN 'Rajamangala University of Technology Lanna' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา'
  WHEN 'Rajamangala University of Technology Phra Nakhon' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร'
  WHEN 'Rajamangala University of Technology Rattanakosin' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์'
  WHEN 'Rajamangala University of Technology Srivijaya' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย'
  WHEN 'Rajamangala University of Technology Suvarnabhumi' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ'
  WHEN 'Rajamangala University of Technology Tawan-ok' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก'
  WHEN 'Rajamangala University of Technology Thanyaburi' THEN 'มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี'
  WHEN 'Rajanagarindra Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏราชนครินทร์'
  WHEN 'Rambhai Barni Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏรำไพพรรณี'
  WHEN 'Ratchathani University' THEN 'มหาวิทยาลัยราชธานี'
  WHEN 'Rattana Bundit University' THEN 'มหาวิทยาลัยรัตนบัณฑิต'
  WHEN 'Roi Et Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏร้อยเอ็ด'
  WHEN 'Royal Police Cadet Academy' THEN 'วิทยาลัยนายร้อยตำรวจ'
  WHEN 'Royal Thai Air Force Nursing College' THEN 'วิทยาลัยพยาบาลกองทัพอากาศไทย'
  WHEN 'Royal Thai Navy Academy' THEN 'โรงเรียนนายเรือ'
  WHEN 'Royal Thai Navy College of Nursing' THEN 'วิทยาลัยพยาบาลกองทัพเรือ'
  WHEN 'Saint John''s University' THEN 'มหาวิทยาลัยเซนต์จอห์น'
  WHEN 'Sakon Nakhon Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏสกลนคร'
  WHEN 'Shinawatra University' THEN 'มหาวิทยาลัยชินวัตร'
  WHEN 'Sisaket Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏศรีสะเกษ'
  WHEN 'Songkhla Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏสงขลา'
  WHEN 'South-East Asia University' THEN 'มหาวิทยาลัยอุเทนถวาย'
  WHEN 'Sripatum University' THEN 'มหาวิทยาลัยศรีปทุม'
  WHEN 'Srisavarindhira Thai Red Cross Institute of Nursing' THEN 'สถาบันการพยาบาลศรีสวรินทิรา'
  WHEN 'Stamford International University' THEN 'มหาวิทยาลัยนานาชาติแสตมฟอร์ด'
  WHEN 'Suan Dusit University' THEN 'มหาวิทยาลัยสวนดุสิต'
  WHEN 'Suan Sunandha Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏสวนสุนันทา'
  WHEN 'Sukhothai Thammathirat Open University' THEN 'มหาวิทยาลัยสุโขทัยธรรมาธิราช'
  WHEN 'Suranaree University of Technology' THEN 'มหาวิทยาลัยเทคโนโลยีสุรนารี'
  WHEN 'Suratthani Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏสุราษฎร์ธานี'
  WHEN 'Surin Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏสุรินทร์'
  WHEN 'Thailand National Sports University' THEN 'มหาวิทยาลัยการกีฬาแห่งชาติ'
  WHEN 'Thaksin University' THEN 'มหาวิทยาลัยทักษิณ'
 WHEN 'Bangkok Suvarnabhumi University' THEN 'มหาวิทยาลัยกรุงเทพสุวรรณภูมิ'
 WHEN 'Dusit Thani College' THEN 'วิทยาลัยดุสิตธานี'
 WHEN 'International Buddhist College' THEN 'วิทยาลัยพุทธศาสนานานาชาติ'
 WHEN 'Kantana Institute' THEN 'สถาบันกันตนา'
 WHEN 'Nation University ( Yonok University )' THEN 'มหาวิทยาลัยเนชั่น'
 WHEN 'National Defence College' THEN 'วิทยาลัยป้องกันราชอาณาจักร'
 WHEN 'National Institute of Development Administration (NIDA)' THEN 'สถาบันบัณฑิตพัฒนบริหารศาสตร์'
 WHEN 'Panyapiwat Institute of Management' THEN 'สถาบันการจัดการปัญญาภิวัฒน์'
 WHEN 'Southeast Bangkok College' THEN 'วิทยาลัยเซาธ์อีสท์บางกอก'
 WHEN 'St Theresa International College' THEN 'วิทยาลัยนานาชาติเซนต์เทเรซา'
 WHEN 'Suvarnabhumi Institute of Technology' THEN 'สถาบันเทคโนโลยีสุวรรณภูมิ'
 WHEN 'Thai-Nichi Institute of Technology' THEN 'สถาบันเทคโนโลยีไทย-ญี่ปุ่น'
 WHEN 'The University of Central Thailand' THEN 'มหาวิทยาลัยภาคกลาง'
 WHEN 'Thepsatri Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏเทพสตรี'
 WHEN 'Thonburi University' THEN 'มหาวิทยาลัยธนบุรี'
  WHEN 'The Eastern University of Management and Technology' THEN 'มหาวิทยาลัยอีสเทิร์นเอเชีย (การจัดการและเทคโนโลยี)'
  WHEN 'The Far Eastern University' THEN 'มหาวิทยาลัยอีสเทิร์น'
 WHEN 'Ubon Ratchathani Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏอุบลราชธานี'
 WHEN 'Ubon Ratchathani University' THEN 'มหาวิทยาลัยอุบลราชธานี'
 WHEN 'Udon Thani Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏอุดรธานี'
 WHEN 'University of Phayao' THEN 'มหาวิทยาลัยพะเยา'
 WHEN 'Uttaradit Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏอุตรดิตถ์'
 WHEN 'Valaya Alongkorn Rajabhat University' THEN 'มหาวิทยาลัยราชภัฏวไลยอลงกรณ์ ในพระบรมราชูปถัมภ์'
 WHEN 'Vongchavalitkul University' THEN 'มหาวิทยาลัยวงษ์ชวลิตกุล'
 WHEN 'Webster University Thailand' THEN 'มหาวิทยาลัยเว็บสเตอร์ ประเทศไทย'
 WHEN 'Western University' THEN 'มหาวิทยาลัยเวสเทิร์น'
  ELSE thname
END;
