export const COUNTRY_DATA = [
  { name: "Thailand", nationality: "Thai", dialCode: "+66" },
  { name: "Afghanistan", nationality: "Afghan", dialCode: "+93" },
  { name: "Argentina", nationality: "Argentine", dialCode: "+54" },
  { name: "Australia", nationality: "Australian", dialCode: "+61" },
  { name: "Brazil", nationality: "Brazilian", dialCode: "+55" },
  { name: "Cambodia", nationality: "Cambodian", dialCode: "+855" },
  { name: "Canada", nationality: "Canadian", dialCode: "+1" },
  { name: "China", nationality: "Chinese", dialCode: "+86" },
  { name: "France", nationality: "French", dialCode: "+33" },
  { name: "Germany", nationality: "German", dialCode: "+49" },
  { name: "India", nationality: "Indian", dialCode: "+91" },
  { name: "Indonesia", nationality: "Indonesian", dialCode: "+62" },
  { name: "Italy", nationality: "Italian", dialCode: "+39" },
  { name: "Japan", nationality: "Japanese", dialCode: "+81" },
  { name: "Laos", nationality: "Laotian", dialCode: "+856" },
  { name: "Malaysia", nationality: "Malaysian", dialCode: "+60" },
  { name: "Myanmar", nationality: "Burmese", dialCode: "+95" },
  { name: "Netherlands", nationality: "Dutch", dialCode: "+31" },
  { name: "New Zealand", nationality: "New Zealander", dialCode: "+64" },
  { name: "Philippines", nationality: "Filipino", dialCode: "+63" },
  { name: "Russia", nationality: "Russian", dialCode: "+7" },
  { name: "Singapore", nationality: "Singaporean", dialCode: "+65" },
  { name: "South Korea", nationality: "South Korean", dialCode: "+82" },
  { name: "Spain", nationality: "Spanish", dialCode: "+34" },
  { name: "Sweden", nationality: "Swedish", dialCode: "+46" },
  { name: "Switzerland", nationality: "Swiss", dialCode: "+41" },
  { name: "Taiwan", nationality: "Taiwanese", dialCode: "+886" },
  { name: "United Kingdom", nationality: "British", dialCode: "+44" },
  { name: "United States", nationality: "American", dialCode: "+1" },
  { name: "Vietnam", nationality: "Vietnamese", dialCode: "+84" },
  { name: "Other", nationality: "Other", dialCode: "" }
];