export const POSITION_OPTIONS: string[] = [
  // --- Software / Engineering ---
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Frontend Engineer",
  "Web Developer",
  "Backend Developer",
  "Backend Engineer",
  "Full Stack Developer",
  "Application Developer",
  "UI Engineer",
  "Mobile Engineer",
  "Software Engineer Intern",
  "Web Developer Intern",
  "Backend Engineer Intern",
  "Frontend Developer (Web)",

  // --- Data / Analytics ---
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Big Data Engineer",
  "Data Governance Analyst",
  "BI Analyst",
  "Data/BI Engineer",
  "Business Intelligence Analyst",

  // --- AI / ML / Research ---
  "AI Developer",
  "AI Engineer",
  "GenAI Engineer",
  "Machine Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Robotics Engineer",
  "AI Research Intern",

  // --- DevOps / Cloud / SRE ---
  "DevOps Engineer",
  "SRE Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Platform Engineer",

  // --- Security ---
  "Cybersecurity Analyst",
  "Security Engineer",
  "SOC Analyst",
  "AppSec Engineer",
  "Security Engineer Intern",
  "Penetration Tester",

  // --- QA / Testing ---
  "Automation QA Engineer",
  "QA Engineer",
  "Quality Assurance Engineer",
  "SDET",
  "QA Tester",
  "Manual QA Engineer",
  "Test Engineer",

  // --- Design / Product ---
  "UI/UX Designer",
  "UI Engineer",
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Design Researcher",
  "Project Manager",
  "Program Manager",
  "Product Manager",
  "Product Marketing Manager",

  // --- Business / Finance / HR / Operations ---
  "Business Analyst",
  "Operations Analyst",
  "Operations Intern",
  "Project Coordinator",
  "Project Coordinator Intern",
  "Business Operations Intern",
  "Compliance Analyst Intern",
  "Risk Analyst Intern",
  "HR",
  "Accounting",
  "Finance",
  "Operations",
  "Engineering",
  "Marketing",
  "Sales",

  // --- Intern-focused / Marketing / Sales / CS / Support ---
  "Marketing Intern",
  "Marketing Specialist",
  "Brand Marketing Intern",
  "Digital Marketing",
  "Digital Marketing Specialist",
  "HR Intern",
  "Recruitment Intern",
  "HR Assistant",
  "Finance Intern",
  "Financial Analyst Intern",
  "Accounting Intern",
  "Bookkeeper Intern",
  "Graphic Designer",
  "Content Designer",
  "Content Writer",
  "Technical Writer",
  "Copywriter Intern",
  "Sales Intern",
  "Sales Development Representative",
  "Account Executive Intern",
  "Business Development Intern",
  "Partnerships Intern",
  "Customer Success Intern",
  "Client Success Intern",
  "Customer Support Intern",
  "Technical Support Intern",
  "IT Support Intern",

  // --- Mobile / Apps ---
  "Mobile Developer",
  "Android Developer",
  "iOS Developer",
  "React Native Developer",
  "Flutter Developer",

  // --- Legacy/generic positions used by some older UI ---
];
