-- Add default UUID generation for all id columns
ALTER TABLE "University" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CandidateProfile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CompanyProfile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "Skills" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "WorkHistory" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CertificateFile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CandidateContactFile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CompanyEmail" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "CompanyPhone" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "UserSkill" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
